Repository Jujulego/lucifer, pull requests merged in 2021-03, with the labels that each got.

#320 Fix Seeder
  .github/workflows/docs.yml
  .github/workflows/prod.yml
  .github/workflows/terraform-plan.yml
  .github/workflows/tests.yml
  apps/lucifer-api/scripts/seed.ts
  yarn.lock
Labels: bug

#327 Upgrade nx
  package.json
  yarn.lock
Labels: dependencies

#321 Typeorm generator
  apps/lucifer-api/ormconfig.json
  apps/lucifer-api/src/db/migrations.ts
  apps/lucifer-api/src/db/migrations/0001-local-user.migration.ts
  apps/lucifer-api/src/db/migrations/0002-project.migration.ts
  apps/lucifer-api/src/db/migrations/0003-variable.migration.ts
  apps/lucifer-api/src/db/migrations/index.ts
  package.json
  tools/executors/db-migrate/index.ts
  tools/executors/deploy/index.ts
  tools/executors/deploy/schema.json
  tools/executors/executors.json
  tools/executors/gen-migration/index.ts
  tools/executors/gen-migration/schema.json
  tools/executors/utils.ts
  tools/generators/collection.json
  tools/generators/db-migration/files/__number__-__name@dasherize__.migration.ts.template
  tools/generators/db-migration/files/index.ts.template
  tools/generators/db-migration/index.ts
  tools/generators/db-migration/schema.json
  tools/utils/typeorm.ts
  workspace.json
  yarn.lock
Labels: enhancement

#370 Upgrade nx
  package.json
  workspace.json
  yarn.lock
Labels: dependencies
